### ISSUE TITLE
Porting AAR with V4 SafeJobIntentService dependency.

### ISSUE THREAD

**Issue by EJAtPhunWare** [xamarin/AndroidSupportComponents#164]
### Xamarin.Android Version (eg: 6.0):

Version: 9.1.8.0 (Visual Studio Community)

### Operating System & Version (eg: Mac OSX 10.11):

Mac OSX 10.13.6

### Support Libraries Version (eg: 23.3.0):

6.0 (API level 23)
7.1 (API level 25)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 26.0.0

### Describe your Issue:

Java.Lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/SafeJobIntentService; ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v4.app.SafeJobIntentService" on path: DexPathList[[zip file "/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/lib/x86, /data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk!/lib/x86, /system/lib]]
  at java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.SafeJobIntentService" on path: DexPathList[[zip file "/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/lib/x86, /data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk!/lib/x86, /system/lib]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at com.phunware.core.analytics.PwAnalyticsModule.getInstance(PwAnalyticsModule.java:77)
  at at com.phunware.core.CoreSessionImp.registerKeys(CoreSessionImp.java:747)
  at at com.phunware.core.PwCoreSession.registerKeys(PwCoreSession.java:351)
  at at md5e960f7a142c17ddf65e9ac38daa3ade0.MainActivity.n_onCreate(Native Method)
  at at md5e960f7a142c17ddf65e9ac38daa3ade0.MainActivity.onCreate(MainActivity.java:29)
  at at android.app.Activity.performCreate(Activity.java:7136)
  at at android.app.Activity.performCreate(Activity.java:7127)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:193)
  at at android.app.ActivityThread.main(ActivityThread.java:6669)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  --- End of inner exception stack trace ---
  at java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/SafeJobIntentService;
  at at com.phunware.core.analytics.PwAnalyticsModule.getInstance(PwAnalyticsModule.java:77)
  at at com.phunware.core.CoreSessionImp.registerKeys(CoreSessionImp.java:747)
  at at com.phunware.core.PwCoreSession.registerKeys(PwCoreSession.java:351)
  at at md5e960f7a142c17ddf65e9ac38daa3ade0.MainActivity.n_onCreate(Native Method)
  at at md5e960f7a142c17ddf65e9ac38daa3ade0.MainActivity.onCreate(MainActivity.java:29)
  at at android.app.Activity.performCreate(Activity.java:7136)
  at at android.app.Activity.performCreate(Activity.java:7127)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:193)
  at at android.app.ActivityThread.main(ActivityThread.java:6669)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.SafeJobIntentService" on path: DexPathList[[zip file "/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/lib/x86, /data/app/com.phunware.pwmapkittest-5-bY-oXdSKzdwcdUEeZRhw==/base.apk!/lib/x86, /system/lib]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at ... 20 more

**Comment by EJAtPhunWare** [comment]
Sorry this is not an issue, was truly missing a reference I didn't see... my bad
