### ISSUE TITLE
Binding AAR library that contains AndroidX cause "NoClassDefFoundError" for "androidx/lifecycle/LifecycleOwner"

### ISSUE THREAD

**Issue by sgong-pdftron** [xamarin/AndroidSupportComponents#223]
### Xamarin.Android Version (eg: 6.0):
Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

Microsoft Visual Studio Professional 2017 
Version 15.9.16
VisualStudio.15.Release/15.9.16+28307.858
Microsoft .NET Framework
Version 4.8.03752

### Support Libraries Version (eg: 23.3.0):

Xamarin.AndroidX.Lifecycle.Common v2.0.0-preview02

### Describe your Issue:
Trying to create an AAR binding library that migrated to AndroidX (written in Java, using class androidx.lifecycle.LifecycleOwner), previously using support library and compiling correctly.

Xamarin.AndroidX.Lifecycle.Common dependency is added to the binding project, however still encountering the following error log:
https://pdftron.s3.amazonaws.com/custom/external/xamarin/androidx/androidx-error.txt

```
4>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.pdftron.pdf.controls.AnnotationToolbar : androidx/lifecycle/LifecycleOwner
4>  java.lang.NoClassDefFoundError: androidx/lifecycle/LifecycleOwner (TaskId:138)
4>    at java.lang.ClassLoader.defineClass1(Native Method) (TaskId:138)
4>    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) (TaskId:138)
4>    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) (TaskId:138)
```

### Steps to Reproduce (with link to sample solution if possible):
Download the sample project, open solution "\projectSrc\PDFNetAndroidXamarin\PDFNetAndroidXamarin.sln"
Clean and build "PDFViewCtrlTools" project.

Link to sample:
http://pdftron.s3.amazonaws.com/custom/external/xamarin/androidx/to-Xamarin.zip

### Include any relevant Exception Stack traces, build logs, adb logs:
https://pdftron.s3.amazonaws.com/custom/external/xamarin/androidx/androidx-error.txt

**Comment by rubenmarrufo** [comment]
Hi! Is there any known workaround for this? Thanks!

**Comment by matheussouza97** [comment]
Any news?

**Comment by moljac** [comment]
`LifecycleOwner` is `ILifecycleOwner` in c# and it is surfaced in preview3.  

https://developer.android.com/reference/androidx/lifecycle/LifecycleOwner

Do you have maybe linker turned on?

Can you give more info on proguard rules?

**Comment by sgong-pdftron** [comment]
@moljac I've included a project that you can reproduce this issue in the first post. Were you able to try that?

**Comment by moljac** [comment]
@sgong-pdftron 
I tried your previous sample, but had to remove (unload) some projects . and was not sure if that was completely OK.
And BTW I really did not have that much time.

if you have something smaller it would be appreciated.

**Comment by moljac** [comment]
@sgong-pdftron Can you try `preview03` of the packages that was released yesterday.

**Comment by sgong-pdftron** [comment]
@moljac Thanks for your reply!

I've just tried preview03 however the exact same error is still present.

The sample project does contain a number of projects however the only projects relevant is the "PDFNetAndroid" and "PDFViewCtrlTools" project. You can unload everything other than these 2 projects.

Clean and build "PDFViewCtrlTools" project will generate the error. Would it be possible if you could give it another try? Thanks!

**Comment by matheussouza97** [comment]
I tried here and got the same error.

**Comment by moljac** [comment]
@sgong-pdftron Thanks for feedback.

> Would it be possible if you could give it another try? Thanks!

Of course. Just, we are (I am) trying to launch AndroidX release 1st. I hope I wll come to this issue in next few days.

@matheussouza97 Thanks for the feedback. Appreciated.
